### ISSUE TITLE
Day 9. CRDT

### ISSUE THREAD

**Issue by dextermallo** [dextermallo/SWE-Question-Daily#9]
- What is CRDT
- Types of CRDT
- Use cases of CRDT

**Comment by dexterchang-tw** [comment]
## What is CRDT

Inconsistencies happen between replicas in distributed systems each computer hosting their replicas without coordination. Moreover, conflicts between replicas, in some circumstances, might not be resolvable. CRDT (Conflict-free replicated data type) is a data structure to **help replicas in each computer can be updated independently and concurrently without coordination**. [1]

## Types of CRDT

CRDT provides **strong eventual consistency** and there're two approaches:

### Operation-based CRDTs

Operation-based CRDTs (a.k.a CmRDTs, commutative replicated data types) update their replicas only by the update operation. For instance:

```markdown
user update replica (10 `+ 10`) -> server1 (replica1 = 10 `+ 10`) -> broadcasting `operation(+10)` ->   server2 (replica2 = 10 `+ 10`)
```

- pros: compared to state-based CRDTs, the packet can be smaller (only transmitting data about update info)
- cons: operations can not be dropped or duplicated when transmitted to the other replicas.

### State-based CRDTs

State-based CRDTs (a.k.a CvRDTs, convergent replicated data types) sends the full local state to other replicas. The others **merged by a function which must follow**:
- Communative: x *  y = y * x
- Associative: a + (b + c) = (a + b) + c
- Idempotent: x * x = x

Example:
```markdown
user update replica (20) -> server1 (replica1 = 20) -> broadcasting `{ order: 1, value: 20 }` ->   server2 (replica2 = `20`)
```

## Use cases of CRDT [1]

- Redis is a distributed, highly available and scalable in-memory database that uses CRDTs for implementing globally distributed databases based on and fully compatible with Redis open source.
- Apple implements CRDTs in the Notes app for syncing offline edits between multiple devices. 

## References

- [1] [Conflict-free replicated data type - Wikipedia](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type)
- [2] [CRDTs in Production](https://www.infoq.com/presentations/crdt-production/)

**Comment by dextermallo** [comment]
## What is CRDT

Inconsistencies happen between replicas in distributed systems each computer hosting their replicas without coordination. Moreover, conflicts between replicas, in some circumstances, might not be resolvable. CRDT (Conflict-free replicated data type) is a data structure to **help replicas in each computer can be updated independently and concurrently without coordination**. [1]

## Types of CRDT

CRDT provides **strong eventual consistency** and there're two approaches:

### Operation-based CRDTs

Operation-based CRDTs (a.k.a CmRDTs, commutative replicated data types) update their replicas only by the update operation. For instance:

```markdown
user update replica (10 `+ 10`) -> server1 (replica1 = 10 `+ 10`) -> broadcasting `operation(+10)` ->   server2 (replica2 = 10 `+ 10`)
```

- pros: compared to state-based CRDTs, the packet can be smaller (only transmitting data about update info)
- cons: operations can not be dropped or duplicated when transmitted to the other replicas.

### State-based CRDTs

State-based CRDTs (a.k.a CvRDTs, convergent replicated data types) sends the full local state to other replicas. The others **merged by a function which must follow**:
- Communative: x *  y = y * x
- Associative: a + (b + c) = (a + b) + c
- Idempotent: x * x = x

Example:
```markdown
user update replica (20) -> server1 (replica1 = 20) -> broadcasting `{ order: 1, value: 20 }` ->   server2 (replica2 = `20`)
```

## Use cases of CRDT [1]

- Redis is a distributed, highly available and scalable in-memory database that uses CRDTs for implementing globally distributed databases based on and fully compatible with Redis open source.
- Apple implements CRDTs in the Notes app for syncing offline edits between multiple devices. 

## References

- [1] [Conflict-free replicated data type - Wikipedia](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type)
- [2] [CRDTs in Production](https://www.infoq.com/presentations/crdt-production/)
